name: org-notify-merge-arxiv-browse  # this name will be referenced downstream
on:
  push:
    branches: [main, develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "arxiv-browse merge completed"